<a href="https://colab.research.google.com/github/Adam3Code/DeepLearning/blob/main/Week3%20Feedforward%20PyTorch/3.1%20What%20is%20pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Credits

This is heavily based on https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used.


PyTorch a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [2]:
import torch

Construct a $5\times 3$ matrix, uninitialized

In [3]:
x = torch.Tensor(5, 3)
print(x)

tensor([[1.4013e-44, 0.0000e+00, 1.1125e-27],
        [0.0000e+00, 3.3631e-44, 0.0000e+00],
        [1.5878e+24, 4.3318e-41, 1.4013e-45],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.4013e-45, 5.6052e-45, 1.4013e-45]])


Construct a randomly initialized matrix

In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0462, 0.2190, 0.7909],
        [0.8575, 0.7015, 0.5017],
        [0.5693, 0.7763, 0.7055],
        [0.8321, 0.9918, 0.0030],
        [0.8518, 0.2111, 0.7241]])


Get its size

In [5]:
print(x.size())

torch.Size([5, 3])


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.

In [6]:
x[1:3] = 2
print(x)

tensor([[0.0462, 0.2190, 0.7909],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.8321, 0.9918, 0.0030],
        [0.8518, 0.2111, 0.7241]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [7]:
y = torch.rand(5, 3)
print(x + y)

tensor([[0.9393, 0.9110, 1.1792],
        [2.7792, 2.5978, 2.1795],
        [2.4333, 2.8809, 2.9523],
        [1.2696, 1.7167, 0.8217],
        [1.3564, 0.7691, 1.3865]])


### 2.2 Addition: syntax 2

In [8]:
print(torch.add(x, y))

tensor([[0.9393, 0.9110, 1.1792],
        [2.7792, 2.5978, 2.1795],
        [2.4333, 2.8809, 2.9523],
        [1.2696, 1.7167, 0.8217],
        [1.3564, 0.7691, 1.3865]])


### 2.3 Addition: giving an output tensor

In [9]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.9393, 0.9110, 1.1792],
        [2.7792, 2.5978, 2.1795],
        [2.4333, 2.8809, 2.9523],
        [1.2696, 1.7167, 0.8217],
        [1.3564, 0.7691, 1.3865]])


### 2.4 Addition: in-place

adds `x` to `y`

In [10]:
y.add_(x)
print(y)

tensor([[0.9393, 0.9110, 1.1792],
        [2.7792, 2.5978, 2.1795],
        [2.4333, 2.8809, 2.9523],
        [1.2696, 1.7167, 0.8217],
        [1.3564, 0.7691, 1.3865]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [11]:
print(x[:, 1])

tensor([0.2190, 2.0000, 2.0000, 0.9918, 0.2111])


**Read later**: 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [12]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [13]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value: the `numpy()` method provides a *view* of the original tensor, not a copy.

In [14]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [15]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a NumPy array
3. now convert it back to a torch tensor

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [16]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

tensor([[0.0462, 0.2190, 0.7909],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.8321, 0.9918, 0.0030],
        [0.8518, 0.2111, 0.7241]], device='cuda:0')
tensor([[0.9393, 0.9110, 1.1792],
        [2.7792, 2.5978, 2.1795],
        [2.4333, 2.8809, 2.9523],
        [1.2696, 1.7167, 0.8217],
        [1.3564, 0.7691, 1.3865]], device='cuda:0')
tensor([[0.9855, 1.1300, 1.9701],
        [4.7792, 4.5978, 4.1795],
        [4.4333, 4.8809, 4.9523],
        [2.1017, 2.7085, 0.8248],
        [2.2081, 0.9802, 2.1106]], device='cuda:0')


In [17]:
!nvidia-smi
import torch
print(torch.cuda.is_available())

Sat Oct  3 11:45:08 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   55C    P0             27W /   70W |     123MiB /  15360MiB |      1%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----