# Credits

This is heavily based on https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used.


PyTorch a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

Construct a $5\times 3$ matrix, uninitialized

In [2]:
x = torch.Tensor(5, 3)
print(x)

tensor([[-8.5136e-39,  4.4542e-41, -8.5137e-39],
        [ 4.4542e-41, -8.5139e-39,  4.4542e-41],
        [-8.5140e-39,  4.4542e-41, -8.5142e-39],
        [ 4.4542e-41, -8.5144e-39,  4.4542e-41],
        [-8.5145e-39,  4.4542e-41, -8.5147e-39]])


Construct a randomly initialized matrix

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2124, 0.6351, 0.5901],
        [0.7275, 0.8846, 0.1554],
        [0.8515, 0.0478, 0.5952],
        [0.1351, 0.0343, 0.9191],
        [0.5713, 0.8695, 0.4353]])


Get its size

In [4]:
print(x.size())

torch.Size([5, 3])


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.

In [5]:
x[1:3] = 2
print(x)

tensor([[0.2124, 0.6351, 0.5901],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.1351, 0.0343, 0.9191],
        [0.5713, 0.8695, 0.4353]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [6]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.0192, 1.1115, 0.7481],
        [2.2473, 2.7876, 2.8044],
        [2.4283, 2.0672, 2.1268],
        [0.3973, 0.3393, 1.6327],
        [1.0542, 1.6548, 0.5888]])


### 2.2 Addition: syntax 2

In [7]:
print(torch.add(x, y))

tensor([[1.0192, 1.1115, 0.7481],
        [2.2473, 2.7876, 2.8044],
        [2.4283, 2.0672, 2.1268],
        [0.3973, 0.3393, 1.6327],
        [1.0542, 1.6548, 0.5888]])


### 2.3 Addition: giving an output tensor

In [8]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.0192, 1.1115, 0.7481],
        [2.2473, 2.7876, 2.8044],
        [2.4283, 2.0672, 2.1268],
        [0.3973, 0.3393, 1.6327],
        [1.0542, 1.6548, 0.5888]])


### 2.4 Addition: in-place

adds `x` to `y`

In [9]:
y.add_(x)
print(y)

tensor([[1.0192, 1.1115, 0.7481],
        [2.2473, 2.7876, 2.8044],
        [2.4283, 2.0672, 2.1268],
        [0.3973, 0.3393, 1.6327],
        [1.0542, 1.6548, 0.5888]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [10]:
print(x[:, 1])

tensor([0.6351, 2.0000, 2.0000, 0.0343, 0.8695])


**Read later**: 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [11]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
b = a.numpy()
print(b)

See how the numpy array changed in value: the `numpy()` method provides a *view* of the original tensor, not a copy.

In [ ]:
a.add_(1)
print(a)
print(b)

### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a NumPy array
3. now convert it back to a torch tensor

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [ ]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")